# Cobra Web Data Model (D2 Format)

# Codes Domain
codes: {
  label: "Codes Domain"
  CODE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    PARENT_CODE_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    CODE_LEVEL: NUMBER(5,0)
    CHILD_COUNT: NUMBER(5,0)
    CHILD_POS: NUMBER(5,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    D1: NVARCHAR2
    D2: NVARCHAR2
    D3: NVARCHAR2
    D4: NVARCHAR2
    D5: NVARCHAR2
    D6: NVARCHAR2
    D7: NVARCHAR2
    D8: NVARCHAR2
    D9: NVARCHAR2
    TAG: VARCHAR2
    BREAKFILE: NVARCHAR2
  }

  CODE_FILE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    CODE_TYPE: VARCHAR2
    TH_FLAGS: VARCHAR2
    DESCRIPTION: NVARCHAR2
    FIELD_NAME: NVARCHAR2
    FIELD_DESCRIPTION: NVARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PAD_CHAR: VARCHAR2
    MAX_LEVEL: NUMBER(19,0)
    LEVEL1: NUMBER(19,0)
    LEVEL2: NUMBER(19,0)
    LEVEL3: NUMBER(19,0)
    LEVEL4: NUMBER(19,0)
    LEVEL5: NUMBER(19,0)
    LEVEL6: NUMBER(19,0)
    LEVEL7: NUMBER(19,0)
    LEVEL8: NUMBER(19,0)
    LEVEL9: NUMBER(19,0)
    LEVEL10: NUMBER(19,0)
    LEVEL11: NUMBER(19,0)
    LEVEL12: NUMBER(19,0)
    LEVEL13: NUMBER(19,0)
    LEVEL14: NUMBER(19,0)
    LEVEL15: NUMBER(19,0)
    LEVEL16: NUMBER(19,0)
    LEVEL17: NUMBER(19,0)
    LEVEL18: NUMBER(19,0)
    LEVEL19: NUMBER(19,0)
    LEVEL20: NUMBER(19,0)
    CODELENGTH: NUMBER(19,0)
  }

  CODE_THRESHOLD: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key,foreign_key]}
    SEQUENCE: NUMBER(19,0)
    SPVF: NUMBER(21,6)
    SPVU: NUMBER(21,6)
    SPPF: NUMBER(5,2)
    SPPU: NUMBER(5,2)
    SCVF: NUMBER(21,6)
    SCVU: NUMBER(21,6)
    SCPF: NUMBER(5,2)
    SCPU: NUMBER(5,2)
    CPVF: NUMBER(21,6)
    CPVU: NUMBER(21,6)
    CPPF: NUMBER(5,2)
    CPPU: NUMBER(5,2)
    CCVF: NUMBER(21,6)
    CCVU: NUMBER(21,6)
    CCPF: NUMBER(5,2)
    CCPU: NUMBER(5,2)
    CAVF: NUMBER(21,6)
    CAVU: NUMBER(21,6)
    CAPF: NUMBER(5,2)
    CAPU: NUMBER(5,2)
    SPF_TL: VARCHAR2
    SPU_TL: VARCHAR2
    SCF_TL: VARCHAR2
    SCU_TL: VARCHAR2
    CPF_TL: VARCHAR2
    CPU_TL: VARCHAR2
    CCF_TL: VARCHAR2
    CCU_TL: VARCHAR2
    CAF_TL: VARCHAR2
    CAU_TL: VARCHAR2
  }

}

# Common Domain
common: {
  label: "Common Domain"
  PRODUCT_CONFIG: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PRODUCT_ID: NUMBER(5,0)
    TYPE: VARCHAR2
    NAME: NVARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    DATA: NCLOB
  }

  PRODUCT_PREFERENCE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PRODUCT_ID: NUMBER(5,0)
    PRIMARY_ENTITY_UID: RAW(16)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    NAME: VARCHAR2
    DATA: VARCHAR2
    SECURE: NUMBER(1,0)
    CREATED_DATE: TIMESTAMP
    CREATED_BY_USER_UID: RAW(16)
    OWNER_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
  }

}

# Fiscal Calendars Domain
fiscal_calendars: {
  label: "Fiscal Calendars Domain"
  FISCAL_CALENDAR: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    DESCRIPTION: NVARCHAR2
    HOURS_MONDAY: NUMBER(6,2)
    HOURS_TUESDAY: NUMBER(6,2)
    HOURS_WEDNESDAY: NUMBER(6,2)
    HOURS_THURSDAY: NUMBER(6,2)
    HOURS_FRIDAY: NUMBER(6,2)
    HOURS_SATURDAY: NUMBER(6,2)
    HOURS_SUNDAY: NUMBER(6,2)
    PATTERN: NVARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DOW_HOURS: VARCHAR2
    DESC00: VARCHAR2
    DESC01: VARCHAR2
    DESC02: VARCHAR2
    DESC03: VARCHAR2
    DESC04: VARCHAR2
    DESC05: VARCHAR2
    DESC06: VARCHAR2
    DESC07: VARCHAR2
    DESC08: VARCHAR2
    DESC09: VARCHAR2
    DESC10: VARCHAR2
    DESC11: VARCHAR2
    DESC12: VARCHAR2
    DESC13: VARCHAR2
    DESC14: VARCHAR2
    DESC15: VARCHAR2
    DESC16: VARCHAR2
    DESC17: VARCHAR2
    DESC18: VARCHAR2
    DESC19: VARCHAR2
  }

  FISCAL_CALENDAR_HOLIDAY: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    FISCAL_CALENDAR_UID: RAW(16) {constraint: [foreign_key]}
    HOLIDAY_DATE: DATE
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
  }

  FISCAL_CALENDAR_PERIOD: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    FISCAL_CALENDAR_UID: RAW(16) {constraint: [foreign_key]}
    END_DATE: DATE
    HOURS: NUMBER(6,2)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    FISCFILE: NVARCHAR2
    FIELD00: NVARCHAR2
    FIELD01: NVARCHAR2
    FIELD02: NVARCHAR2
    FIELD03: NVARCHAR2
    FIELD04: NVARCHAR2
    FIELD05: NVARCHAR2
    FIELD06: NVARCHAR2
    FIELD07: NVARCHAR2
    FIELD08: NVARCHAR2
    FIELD09: NVARCHAR2
    FIELD10: NVARCHAR2
    FIELD11: NVARCHAR2
    FIELD12: NVARCHAR2
    FIELD13: NVARCHAR2
    FIELD14: NVARCHAR2
    FIELD15: NVARCHAR2
    FIELD16: NVARCHAR2
    FIELD17: NVARCHAR2
    FIELD18: NVARCHAR2
    FIELD19: NVARCHAR2
    FLAG01: NVARCHAR2
    FLAG02: NVARCHAR2
    FLAG03: NVARCHAR2
    FLAG04: NVARCHAR2
    FLAG05: NVARCHAR2
    FLAG06: NVARCHAR2
    FLAG07: NVARCHAR2
    FLAG08: NVARCHAR2
    FLAG09: NVARCHAR2
    FLAG10: NVARCHAR2
    FLAG11: NVARCHAR2
    FLAG12: NVARCHAR2
    FLAG13: NVARCHAR2
    FLAG14: NVARCHAR2
    FLAG15: NVARCHAR2
    FLAG16: NVARCHAR2
    FLAG17: NVARCHAR2
    FLAG18: NVARCHAR2
    FLAG19: NVARCHAR2
  }

  FISCAL_CALENDAR_SET: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    FISCAL_CALENDAR_UID: RAW(16) {constraint: [foreign_key]}
    SET_ID: NVARCHAR2
    LABEL_FORMAT: NVARCHAR2
    LABEL_VALUE: NVARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
  }

  FISCAL_CALENDAR_SET_LABEL: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    FISCAL_CALENDAR_SET_UID: RAW(16) {constraint: [foreign_key]}
    FISCAL_CALENDAR_PERIOD_UID: RAW(16) {constraint: [foreign_key]}
    "LABEL": NVARCHAR2
    FLAG: VARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

}

# Projects Domain
projects: {
  label: "Projects Domain"
  ACCOUNTS: {
    shape: sql_table
    NAME: VARCHAR2
    DESCRIPTION: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    REQUIRED: NUMBER(19,0)
    PROGRAM: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  BATCH: {
    shape: sql_table
    BATCHREP_ID: VARCHAR2
    DIR_ID: VARCHAR2
    FILTER_ID: VARCHAR2
    FILTER_SHARED: NUMBER(19,0)
    LAST_MODIFIED_DATE: TIMESTAMP
    LINE: NUMBER(19,0)
    OWNER_ID: VARCHAR2
    REPORT_ID: VARCHAR2
    SEQUENCE: NUMBER(19,0)
    SORT_ID: VARCHAR2
    SORT_SHARED: NUMBER(19,0)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  BATCHREP: {
    shape: sql_table
    BATCHREP_ID: VARCHAR2
    BATCHREP_UID: VARCHAR2
    DESCRIPTION: VARCHAR2
    LAST_MODIFIED_DATE: TIMESTAMP
    OUTPUT_LOC: VARCHAR2
    OUTPUT_TYPE: VARCHAR2
    OWNER_ID: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PROGRAM: VARCHAR2
    SEQUENCE: NUMBER(19,0)
    SUB_FOLDER: NUMBER(19,0)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  CHNG_REQST: {
    shape: sql_table
    BFINISH: DATE
    BSTART: DATE
    CHNG_NUM: VARCHAR2
    LAST_MODIFIED_DATE: TIMESTAMP
    PERIOD: DATE
    REQST_TYPE: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    SOURCE_PROGRAM: VARCHAR2
    STAGE: VARCHAR2
    TITLE: VARCHAR2
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    SEQUENCE: NUMBER(19,0)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  CHNG_REQST_PROGRAM: {
    shape: sql_table
    CHNG_NUM: VARCHAR2
    LAST_MODIFIED_DATE: TIMESTAMP
    PHASE: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PROGRAM: VARCHAR2
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    SEQUENCE: NUMBER(19,0)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  CLASSRANGES: {
    shape: sql_table
    "CLASS": VARCHAR2
    FIELDNUM: NUMBER(19,0)
    PROGRAM: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    RANGE_KEY: VARCHAR2
    RANGE_VALUE: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  CONNECTION: {
    shape: sql_table
    CONN_ID: VARCHAR2
    CONN_TYPE: VARCHAR2
    DATA: NCLOB
    DESCRIPTION: VARCHAR2
    GRP_ID: VARCHAR2
    LAST_MODIFIED_DATE: TIMESTAMP
    OWNER_ID: VARCHAR2
    READONLY: NUMBER(19,0)
    SEQUENCE: NUMBER(19,0)
    SHARED: NUMBER(19,0)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  COSTDETL: {
    shape: sql_table
    "CLASS": VARCHAR2
    COSTSET: VARCHAR2
    INSTANCE: VARCHAR2
    ORD: NUMBER(19,0)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    LAST_MODIFIED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  "LINK": {
    shape: sql_table
    BFINISH: DATE
    BSTART: DATE
    CA1: VARCHAR2
    CA2: VARCHAR2
    CA3: VARCHAR2
    CAWPID: NUMBER(19,0)
    PROJECT_CAWP_UID: RAW(16) {constraint: [foreign_key]}
    "CLASS": VARCHAR2
    DESCRIPTION: VARCHAR2
    EFDATE: DATE
    ESDATE: DATE
    FCSTCLASS: VARCHAR2
    FULLID: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    LFDATE: DATE
    LSDATE: DATE
    MS_NO: VARCHAR2
    MSWEIGHT: NUMBER(21,6)
    PFINISH: DATE
    PMT: VARCHAR2
    PRJNAME: VARCHAR2
    PROGRAM: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PSTART: DATE
    SFDATE: DATE
    SSDATE: DATE
    STARTPC: NUMBER(19,0)
    UNITSTODO: NUMBER(19,0)
    VALID: VARCHAR2
    WP: VARCHAR2
    SEQUENCE: NUMBER(19,0)
    LAST_MODIFIED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  PROCESSLOG: {
    shape: sql_table
    CONTEXT: VARCHAR2
    DATA: NCLOB
    DIR_ID: VARCHAR2
    ERRORCOUNT: NUMBER(19,0)
    FINISHTIME: TIMESTAMP
    LAST_MODIFIED_DATE: TIMESTAMP
    PROCESS_ID: VARCHAR2
    PROGRESS_PCT: NUMBER(19,0)
    PROGRESS_TEXT: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    STARTTIME: TIMESTAMP
    USR_ABORT: NUMBER(19,0)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    WARNINGCOUNT: NUMBER(19,0)
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

  PROCESSLOGLINK: {
    shape: sql_table
    BATCH_UID: VARCHAR2
    PROCESSLOG_UID: RAW(16) {constraint: [foreign_key]}
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  PROJECT: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    INACTIVE: NUMBER(1,0)
    NAME: NVARCHAR2
    DESCRIPTION: NVARCHAR2
    WBS_CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    OBS_CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    CHANGE_NUMBER_CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    CLIN_CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    FISCAL_CALENDAR_UID: RAW(16) {constraint: [foreign_key]}
    RESOURCE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    RATE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    RW_FISCAL_CALENDAR_UID: RAW(16) {constraint: [foreign_key]}
    PERIOD_START: DATE
    PERIOD_END: DATE
    SPTYPE: NUMBER(5,0)
    AUDIT_LOG_LEVEL: VARCHAR2
    SCALECAP: VARCHAR2
    BASELINE_START: DATE
    BASELINE_FINISH: DATE
    FORECAST_FINISH: DATE
    SCALEFAC: NUMBER(5,0)
    FEE_PRCENT: NUMBER(21,6)
    CTC: NUMBER(21,6)
    AUW: NUMBER(21,6)
    OTC: NUMBER(21,6)
    CBB: NUMBER(21,6)
    FEE: NUMBER(21,6)
    MR: NUMBER(21,6)
    UB: NUMBER(21,6)
    CEILING: NUMBER(21,6)
    LRE: NUMBER(21,6)
    ESTCEILING: NUMBER(21,6)
    ESTMR: NUMBER(21,6)
    ESTUB: NUMBER(21,6)
    BASELINED: NUMBER(1,0)
    OTB: NUMBER(21,6)
    CCN_USEBDN: NUMBER(1,0)
    CCN_REQUIRED: NUMBER(1,0)
    CAM_REQUIRED: NUMBER(1,0)
    CLASSIFICATION: VARCHAR2
    EVMS_ACCEPTANCE: NUMBER(10,0)
    EVMS_ACCEPTANCE_DATE: DATE
    OTB_DATE: DATE
    EAC_BEST: NUMBER(21,6)
    EAC_WORST: NUMBER(21,6)
    COMPLETE: DATE
    DEFINITE: DATE
    CURRENCY_SYMBOL: VARCHAR2
    CURRENCY_SYMBOL_RIGHT: NUMBER(1,0)
    ESTPRICE: NUMBER(21,6)
    OTB_MR: NUMBER(21,6)
    ACWP: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    ADDRESS: VARCHAR2
    BAC: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    BATCHNO: NUMBER(19,0)
    BCWP: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    CA_ACTUAL: VARCHAR2
    CA_BD1: VARCHAR2
    CA_BD2: VARCHAR2
    CA_BD3: VARCHAR2
    CA_ID1: VARCHAR2
    CA_ID2: VARCHAR2
    CA_ID3: VARCHAR2
    CALC_FILE: VARCHAR2
    CAMCODE: VARCHAR2
    CCN_BDN: VARCHAR2
    CE_BDN: VARCHAR2
    CE_ID: VARCHAR2
    CITY: VARCHAR2
    CLC_PROMPT: VARCHAR2
    CLIN_CODE: VARCHAR2
    CONT_FLAG: VARCHAR2
    CONT_IDCODE: VARCHAR2
    CONT_IDTYPE: VARCHAR2
    CONT_LOC: VARCHAR2
    CONT_NAME: VARCHAR2
    CONT_NO: VARCHAR2
    CONT_PHASE: VARCHAR2
    CONT_PROGRAM: VARCHAR2
    CONT_PROGTYPE: VARCHAR2
    CONT_REPEMAIL: VARCHAR2
    CONT_REPN: VARCHAR2
    CONT_REPPHONE: VARCHAR2
    CONT_REPT: VARCHAR2
    CONT_STATEMENT: VARCHAR2
    CONT_TASK: VARCHAR2
    CONT_TYPE: VARCHAR2
    CONTRACT: VARCHAR2
    COUNTRY: VARCHAR2
    EAC: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    FC_TYPE1: VARCHAR2
    FC_TYPE2: VARCHAR2
    FC_TYPE3: VARCHAR2
    FC_TYPE4: VARCHAR2
    FISC_FILE: VARCHAR2
    FISC_RW: VARCHAR2
    IPMR2_CODE: VARCHAR2
    ISMASTER: NUMBER(19,0)
    MGRFILE: VARCHAR2
    MGRTYPE: VARCHAR2
    MPSCODE: VARCHAR2
    OPP_PROJ: VARCHAR2
    P1: VARCHAR2
    P2: VARCHAR2
    P3: VARCHAR2
    P4: VARCHAR2
    P5: VARCHAR2
    P6: VARCHAR2
    P7: VARCHAR2
    P8: VARCHAR2
    P9: VARCHAR2
    PERCENT1: NUMBER(19,0)
    PERCENT2: NUMBER(19,0)
    PERCENT3: NUMBER(19,0)
    PRODVIS: NUMBER(19,0)
    PROGRAM: VARCHAR2
    QUANTITY: NUMBER(19,0)
    RATE_FILE: VARCHAR2
    SHARERATIO: VARCHAR2
    STATE: VARCHAR2
    WP_BDN: VARCHAR2
    WP_ID: VARCHAR2
    ZIP: VARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  PROJECT_AUDIT_LOG: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_CONTROL_ACCOUNT_NAME: NVARCHAR2
    PROJECT_WORK_PACKAGE_NAME: NVARCHAR2
    PROJECT_CAWP_RESOURCE_NAME: NVARCHAR2
    PERIOD_END: DATE
    REFERENCE_NUMBER: NUMBER(10,0)
    TRANSACTION_UID: RAW(16)
    DEBIT: NUMBER(1,0)
    CREDIT: NUMBER(1,0)
    AMOUNT: NUMBER(21,6)
    LOG_COMMENT: NVARCHAR2
    CPR3: NUMBER(1,0)
    CHANGE_NUMBER: NVARCHAR2
    SIGNIFICANT_CHANGE: NUMBER(1,0)
    HOURS: NUMBER(6,2)
    CLIN_NAME: NVARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: VARCHAR2
  }

  PROJECT_AUDIT_LOG_ACCOUNTS: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    REFERENCE_NUMBER: NUMBER(10,0)
    TRANSACTION_UID: NVARCHAR2
    PERIOD_END: DATE
    "LABEL": NVARCHAR2
    LOG_COMMENT: NVARCHAR2
    UB: NUMBER(21,6)
    MR: NUMBER(21,6)
    AUW: NUMBER(21,6)
    CTC: NUMBER(21,6)
    DB: NUMBER(21,6)
    EAC: NUMBER(21,6)
    FEE: NUMBER(21,6)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: VARCHAR2
  }

  PROJECT_AUDIT_LOG_HISTORY: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_CAWP_UID: RAW(16)
    PERIOD_END: DATE
    BAC: NUMBER(21,6)
    EAC: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    ACWP: NUMBER(21,6)
    BCWS_HRS: NUMBER(6,2)
    BCWP_HRS: NUMBER(6,2)
    ACWP_HRS: NUMBER(6,2)
    BAC_HRS: NUMBER(6,2)
    EAC_HRS: NUMBER(6,2)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    CAWP: NUMBER(19,0)
    PROGRAM: VARCHAR2
  }

  PROJECT_AUDIT_LOG_TPHASE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_AUDIT_LOG_UID: RAW(16) {constraint: [foreign_key]}
    TRANSACTION_UID: RAW(16)
    TPHASE_DATE: TIMESTAMP
    HOURS: NUMBER(6,2)
    AMOUNT: NUMBER(21,6)
    SEQUENCE: NUMBER(19,0)
    PROGRAM: VARCHAR2
  }

  PROJECT_CALC_RESULT: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    RESULT_CODE: VARCHAR2
    RESULT: VARCHAR2
    CURRENCY: NUMBER(1,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    EXPRESSION: VARCHAR2
    PROGRAM: VARCHAR2
  }

  PROJECT_CAWP: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    OBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
    WBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
    PARENT_PROJECT_CAWP_UID: RAW(16) {constraint: [foreign_key]}
    CAM_CODE_UID: RAW(16) {constraint: [foreign_key]}
    CLIN_CODE_UID: RAW(16) {constraint: [foreign_key]}
    IS_WP: NUMBER(1,0)
    BASELINE_START: DATE
    BASELINE_FINISH: DATE
    ACTUAL_START: DATE
    ACTUAL_FINISH: DATE
    EARLY_START: DATE
    EARLY_FINISH: DATE
    LATE_START: DATE
    LATE_FINISH: DATE
    PENDING_START: DATE
    PENDING_FINISH: DATE
    FORECAST_START: DATE
    FORECAST_FINISH: DATE
    STATUS: VARCHAR2
    EVT: VARCHAR2
    START_PERCENT: NUMBER(5,2)
    PERCENT_COMPLETE: NUMBER(5,2)
    UNITS_TO_DO: NUMBER(21,6)
    UNITS_COMPLETE: NUMBER(21,6)
    ACWP: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    ACWPCP: NUMBER(21,6)
    ACWPCP_HRS: NUMBER(21,6)
    APPLINK: NUMBER(19,0)
    BAC: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWPCP: NUMBER(21,6)
    BCWPCP_HRS: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BCWSCP: NUMBER(21,6)
    BCWSCP_HRS: NUMBER(21,6)
    C1: VARCHAR2
    C10: VARCHAR2
    C11: VARCHAR2
    C12: VARCHAR2
    C13: VARCHAR2
    C14: VARCHAR2
    C15: VARCHAR2
    C16: VARCHAR2
    C17: VARCHAR2
    C18: VARCHAR2
    C19: VARCHAR2
    C2: VARCHAR2
    C20: VARCHAR2
    C3: VARCHAR2
    C4: VARCHAR2
    C5: VARCHAR2
    C6: VARCHAR2
    C7: VARCHAR2
    C8: VARCHAR2
    C9: VARCHAR2
    CA1: VARCHAR2
    CA2: VARCHAR2
    CA3: VARCHAR2
    CAWPID: NUMBER(19,0)
    CL_BATCH: NUMBER(19,0)
    EAC: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    EAC_NONLAB: NUMBER(21,6)
    EOC: VARCHAR2
    FLAG: VARCHAR2
    OP_BATCH: NUMBER(19,0)
    USER_CHR01: VARCHAR2
    USER_CHR02: VARCHAR2
    USER_CHR03: VARCHAR2
    USER_CHR04: VARCHAR2
    USER_CHR05: VARCHAR2
    USER_DTE01: DATE
    USER_DTE02: DATE
    USER_DTE03: DATE
    USER_DTE04: DATE
    USER_DTE05: DATE
    USER_NUM01: NUMBER(21,6)
    USER_NUM02: NUMBER(21,6)
    USER_NUM03: NUMBER(21,6)
    USER_NUM04: NUMBER(21,6)
    USER_NUM05: NUMBER(21,6)
    PROGRAM: VARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    RESERVED1: NVARCHAR2
  }

  PROJECT_CAWP_RESOURCE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_CAWP_UID: RAW(16) {constraint: [foreign_key]}
    RESOURCES_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_COST_CLASS_UID: RAW(16) {constraint: [foreign_key]}
    SPREAD_CURVE_UID: RAW(16) {constraint: [foreign_key]}
    RSSTART: DATE
    RSFINISH: DATE
    BAC: NUMBER(21,6)
    ETC: NUMBER(21,6)
    PERCENT_COMPLETE: NUMBER(5,2)
    PF: NUMBER(21,6)
    GA_PF: NUMBER(21,6)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: VARCHAR2
    C1: NVARCHAR2
    C2: NVARCHAR2
    C3: NVARCHAR2
    C4: NVARCHAR2
    C5: NVARCHAR2
    C6: NVARCHAR2
    C7: NVARCHAR2
    C8: NVARCHAR2
    C9: NVARCHAR2
    CAWPID: NUMBER(19,0)
    CECODE: VARCHAR2
    "CLASS": VARCHAR2
    SPREADNAME: VARCHAR2
  }

  PROJECT_CAWP_RESOURCE_TPHASE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_CAWP_RESOURCE_UID: RAW(16) {constraint: [foreign_key]}
    TPHASE_DATE: DATE
    RESULT1: NUMBER(21,6)
    RESULT2: NUMBER(21,6)
    RESULT3: NUMBER(21,6)
    RESULT4: NUMBER(21,6)
    RESULT5: NUMBER(21,6)
    RESULT6: NUMBER(21,6)
    RESULT7: NUMBER(21,6)
    RESULT8: NUMBER(21,6)
    RESULT9: NUMBER(21,6)
    RESULT10: NUMBER(21,6)
    RESULT11: NUMBER(21,6)
    RESULT12: NUMBER(21,6)
    RESULT13: NUMBER(21,6)
    RESULT14: NUMBER(21,6)
    RESULT15: NUMBER(21,6)
    RESULT16: NUMBER(21,6)
    RESULT17: NUMBER(21,6)
    RESULT18: NUMBER(21,6)
    RESULT19: NUMBER(21,6)
    RESULT20: NUMBER(21,6)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: NVARCHAR2
    "CLASS": NVARCHAR2
    CECODE: NVARCHAR2
    BATCHNO: NUMBER(10,0)
    CAWPID: NUMBER(19,0)
    COM: NUMBER(19,0)
    DIRECT: NUMBER(19,0)
    FEE: NUMBER(19,0)
    FRINGE: NUMBER(19,0)
    FTE: NUMBER(19,0)
    GANDA: NUMBER(19,0)
    HOURS: NUMBER(19,0)
    OVERHEAD: NUMBER(19,0)
  }

  PROJECT_CAWP_TOTAL: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key,foreign_key]}
    ACWP: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BAC: NUMBER(21,6)
    EAC: NUMBER(21,6)
    EAC_NONLAB: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    ACWPCP: NUMBER(21,6)
    BCWPCP: NUMBER(21,6)
    BCWSCP: NUMBER(21,6)
    ACWPCP_HRS: NUMBER(21,6)
    BCWPCP_HRS: NUMBER(21,6)
    BCWSCP_HRS: NUMBER(21,6)
  }

  PROJECT_CONTROL_ACCOUNT: {
    shape: sql_table
    ACTUAL_FINISH: DATE
    ACTUAL_START: DATE
    ACWP: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    ACWPCP: NUMBER(21,6)
    ACWPCP_HRS: NUMBER(21,6)
    APPLINK: NUMBER(10,0)
    BAC: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    BASELINE_FINISH: DATE
    BASELINE_START: DATE
    BCWP: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWPCP: NUMBER(21,6)
    BCWPCP_HRS: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BCWSCP: NUMBER(21,6)
    BCWSCP_HRS: NUMBER(21,6)
    C1: NVARCHAR2
    C10: NVARCHAR2
    C11: NVARCHAR2
    C12: NVARCHAR2
    C13: NVARCHAR2
    C14: NVARCHAR2
    C15: NVARCHAR2
    C16: NVARCHAR2
    C17: NVARCHAR2
    C18: NVARCHAR2
    C19: NVARCHAR2
    C2: NVARCHAR2
    C20: NVARCHAR2
    C3: NVARCHAR2
    C4: NVARCHAR2
    C5: NVARCHAR2
    C6: NVARCHAR2
    C7: NVARCHAR2
    C8: NVARCHAR2
    C9: NVARCHAR2
    CA1: NVARCHAR2
    CA2: NVARCHAR2
    CA3: NVARCHAR2
    CL_BATCH: NUMBER(10,0)
    CONTRACT_CLIN_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    EAC: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    EAC_NONLAB: NUMBER(21,6)
    EARLY_FINISH: DATE
    EARLY_START: DATE
    EOC: VARCHAR2
    FLAG: VARCHAR2
    FORECAST_FINISH: DATE
    FORECAST_START: DATE
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    LATE_FINISH: DATE
    LATE_START: DATE
    MANAGER_USER_UID: RAW(16)
    NAME: NVARCHAR2
    OBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
    OP_BATCH: NUMBER(10,0)
    PC_COMP: NUMBER(21,6)
    PENDING_FINISH: DATE
    PENDING_START: DATE
    PMT: VARCHAR2
    PROGRAM: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    RESERVED1: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    STARTPC: NUMBER(5,0)
    UNITS_COMP: NUMBER(21,6)
    UNITSTODO: NUMBER(21,6)
    USER_CHR01: VARCHAR2
    USER_CHR02: VARCHAR2
    USER_CHR03: VARCHAR2
    USER_CHR04: VARCHAR2
    USER_CHR05: VARCHAR2
    USER_DTE01: DATE
    USER_DTE02: DATE
    USER_DTE03: DATE
    USER_DTE04: DATE
    USER_DTE05: DATE
    USER_NUM01: NUMBER(21,6)
    USER_NUM02: NUMBER(21,6)
    USER_NUM03: NUMBER(21,6)
    USER_NUM04: NUMBER(21,6)
    USER_NUM05: NUMBER(21,6)
    WBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
    WP: VARCHAR2
  }

  PROJECT_CONTROL_ACCOUNT_TOTAL: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key,foreign_key]}
    ACWP: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BAC: NUMBER(21,6)
    EAC: NUMBER(21,6)
    EAC_NONLAB: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    ACWPCP: NUMBER(21,6)
    BCWPCP: NUMBER(21,6)
    BCWSCP: NUMBER(21,6)
    ACWPCP_HRS: NUMBER(21,6)
    BCWPCP_HRS: NUMBER(21,6)
    BCWSCP_HRS: NUMBER(21,6)
  }

  PROJECT_COST_CLASS: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    RATE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    FISCAL_CALENDAR_SET_UID: RAW(16) {constraint: [foreign_key]}
    COST_CLASS_TYPE: VARCHAR2
    COST_CLASS_LEVEL: VARCHAR2
    REQUIRED: NUMBER(1,0)
    CALC_SOURCE_RESULTS: NUMBER(1,0)
    DATE_SET: VARCHAR2
    BUDGET_SOURCE: VARCHAR2
    FCAST_METHOD: VARCHAR2
    FCAST_SCALE_EAC: VARCHAR2
    FCAST_PERF_FACTOR_LEVEL: VARCHAR2
    FCAST_PERF_FACTOR_CODE: VARCHAR2
    FCAST_PERF_FACTOR_WEIGHT_A: NUMBER(21,6)
    FCAST_PERF_FACTOR_WEIGHT_B: NUMBER(21,6)
    FCAST_PCT_RANGE1_PERCENT: NUMBER(5,0)
    FCAST_PCT_RANGE2_PERCENT: NUMBER(5,0)
    FCAST_PCT_RANGE3_PERCENT: NUMBER(5,0)
    FCAST_PCT_RANGE1_METHOD: VARCHAR2
    FCAST_PCT_RANGE2_METHOD: VARCHAR2
    FCAST_PCT_RANGE3_METHOD: VARCHAR2
    FCAST_PCT_RANGE4_METHOD: VARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    READONLY: NUMBER(5,0)
    RANGE_FIELDID: VARCHAR2
    IS_BCWS: NUMBER(19,0)
    IS_ACWP: NUMBER(19,0)
    FC_DATESET: VARCHAR2
    PLUSPLUS: VARCHAR2
    MINUSPLUS: VARCHAR2
    MINUSMINUS: VARCHAR2
    CLASSCAL: VARCHAR2
    CLASSRATE: VARCHAR2
    PROGRAM: VARCHAR2
  }

  PROJECT_COST_CLASS_LINK: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PARENT_PROJECT_COST_CLASS_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_COST_CLASS_UID: RAW(16) {constraint: [foreign_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: VARCHAR2
    "CLASS": VARCHAR2
    CONTAINEDCLASS: VARCHAR2
  }

  PROJECT_COST_SET: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    REQUIRED: NUMBER(1,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    PROGRAM: NVARCHAR2
  }

  PROJECT_COST_SET_CLASS: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_COST_SET_UID: RAW(16) {constraint: [foreign_key]}
    PROJECT_COST_CLASS_UID: RAW(16) {constraint: [foreign_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    PROGRAM: VARCHAR2
    COST: VARCHAR2
    "CLASS": VARCHAR2
  }

  PROJECT_COST_TOTAL: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key,foreign_key]}
    ACWP: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BAC: NUMBER(21,6)
    EAC: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
  }

  PROJECT_SUBPROJECT: {
    shape: sql_table
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    SUBPROJECT_UID: RAW(16) {constraint: [foreign_key]}
    MASTER: NVARCHAR2
    SUBPROGRAM: NVARCHAR2
  }

  PROJECT_WORK_PACKAGE: {
    shape: sql_table
    ACTUAL_FINISH: DATE
    ACTUAL_START: DATE
    APPORTIONED_PROJECT_WP_UID: RAW(16) {constraint: [foreign_key]}
    BASELINE_FINISH: DATE
    BASELINE_START: DATE
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    EARLY_FINISH: DATE
    EARLY_START: DATE
    EVT: VARCHAR2
    FORECAST_FINISH: DATE
    FORECAST_START: DATE
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    LATE_FINISH: DATE
    LATE_START: DATE
    MANAGER_USER_UID: RAW(16)
    NAME: NVARCHAR2
    OBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
    PENDING_FINISH: DATE
    PENDING_START: DATE
    PERCENT_COMPLETE: NUMBER(5,2)
    PROJECT_CONTROL_ACCOUNT_UID: RAW(16) {constraint: [foreign_key]}
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    START_PERCENT: NUMBER(5,2)
    UNITS_COMPLETE: NUMBER(21,6)
    UNITS_TO_DO: NUMBER(21,6)
    WBS_CODE_UID: RAW(16) {constraint: [foreign_key]}
  }

  PROJECT_WORK_PACKAGE_TOTAL: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key,foreign_key]}
    ACWP: NUMBER(21,6)
    BCWP: NUMBER(21,6)
    BCWS: NUMBER(21,6)
    BAC: NUMBER(21,6)
    EAC: NUMBER(21,6)
    EAC_NONLAB: NUMBER(21,6)
    ACWP_HRS: NUMBER(21,6)
    BCWP_HRS: NUMBER(21,6)
    BCWS_HRS: NUMBER(21,6)
    BAC_HRS: NUMBER(21,6)
    EAC_HRS: NUMBER(21,6)
    ACWPCP: NUMBER(21,6)
    BCWPCP: NUMBER(21,6)
    BCWSCP: NUMBER(21,6)
    ACWPCP_HRS: NUMBER(21,6)
    BCWPCP_HRS: NUMBER(21,6)
    BCWSCP_HRS: NUMBER(21,6)
  }

  PROJECT_WP_MILESTONE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PROJECT_WORK_PACKAGE_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    BASELINE_FINISH: DATE
    ACTUAL_FINISH: DATE
    STATUS: VARCHAR2
    WEIGHT: NUMBER(21,6)
    PERCENT_COMPLETE: NUMBER(5,2)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    CL_BATCH: NUMBER(19,0)
    PROGRAM: VARCHAR2
    CAWPID: NUMBER(19,0)
    FORECAST_FINISH: DATE
  }

  RCUTOFF: {
    shape: sql_table
    HOURS: NUMBER(21,6)
    INSTANCE: VARCHAR2
    PD_FINISH: DATE
    PD_START: DATE
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  TEMP_CAWPID: {
    shape: sql_table
    CAWPID: NUMBER(19,0)
    PROJECT_CAWP_UID: RAW(16) {constraint: [foreign_key]}
    INSTANCE: VARCHAR2
    PROGRAM: VARCHAR2
    PROJECT_UID: RAW(16) {constraint: [foreign_key]}
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  TEMP_CHAR: {
    shape: sql_table
    CHAR_VAL: VARCHAR2
    INSTANCE: VARCHAR2
    CREATED_DATE: TIMESTAMP
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  TEMP_DIR: {
    shape: sql_table
    DIR_ID: VARCHAR2
    INSTANCE: VARCHAR2
    CREATED_DATE: TIMESTAMP
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  WST_DCT: {
    shape: sql_table
    TABLE_TYPE: VARCHAR2
    FLD_NAME: VARCHAR2
    TYPE: VARCHAR2
    LENGTH: NUMBER(19,0)
    SCALE: NUMBER(19,0)
    COL_FLAGS: NUMBER(19,0)
    SYS_NAME: VARCHAR2
    USR_NAME: VARCHAR2
    STRING_ID: NUMBER(19,0)
    FKEY_TABLE: VARCHAR2
    FKEY_FLD_NAME: VARCHAR2
    FKEY_REQUIRED: NUMBER(19,0)
    FKEY_VIRTUAL: NUMBER(19,0)
    DEL_FOREIGN_ACTION: VARCHAR2
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  WST_LCK: {
    shape: sql_table
    CONTEXT: VARCHAR2
    CONTEXT_ID: VARCHAR2
    DIR_UID: VARCHAR2
    LAST_MODIFIED_DATE: TIMESTAMP
    LCK_UID: VARCHAR2
    LOCKMODE: VARCHAR2
    MACHINE_ID: VARCHAR2
    PRD_UID: NUMBER(5,0)
    ULI_UID: VARCHAR2
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
  }

}

# Rates Domain
rates: {
  label: "Rates Domain"
  RATE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    RATE_SET_UID: RAW(16) {constraint: [foreign_key]}
    RATE_DATE: DATE
    RATE_VALUE: NUMBER(21,6)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    RATEFILE: VARCHAR2
    RATE_TABLE: VARCHAR2
  }

  RATE_FILE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    DESCRIPTION: NVARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  RATE_SET: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    RATE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    C1: VARCHAR2
    C2: VARCHAR2
    RATEFILE: VARCHAR2
  }

}

# Resources Domain
resources: {
  label: "Resources Domain"
  RESOURCES: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    RESOURCE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    PARENT_RESOURCES_UID: RAW(16) {constraint: [foreign_key]}
    NAME: NVARCHAR2
    CHILD_COUNT: NUMBER(19,0)
    RESOURCE_LEVEL: NUMBER(19,0)
    EOC: VARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    D1: NVARCHAR2
    D2: NVARCHAR2
    D3: NVARCHAR2
    D4: NVARCHAR2
    D5: NVARCHAR2
    D6: NVARCHAR2
    D7: NVARCHAR2
    D8: NVARCHAR2
    D9: NVARCHAR2
    TAG: VARCHAR2
    TH_CAPF: NUMBER(21,6)
    TH_CAPU: NUMBER(21,6)
    TH_CAVF: NUMBER(21,6)
    TH_CAVU: NUMBER(21,6)
    TH_CCPF: NUMBER(21,6)
    TH_CCPU: NUMBER(21,6)
    TH_CCVF: NUMBER(21,6)
    TH_CCVU: NUMBER(21,6)
    TH_CPPF: NUMBER(21,6)
    TH_CPPU: NUMBER(21,6)
    TH_CPVF: NUMBER(21,6)
    TH_CPVU: NUMBER(21,6)
    TH_SCPF: NUMBER(21,6)
    TH_SCPU: NUMBER(21,6)
    TH_SCVF: NUMBER(21,6)
    TH_SCVU: NUMBER(21,6)
    TH_SPPF: NUMBER(21,6)
    TH_SPPU: NUMBER(21,6)
    TH_SPVF: NUMBER(21,6)
    TH_SPVU: NUMBER(21,6)
    CALCFILE: VARCHAR2
    CHILD_POS: NUMBER(5,0)
  }

  RESOURCE_COST_CALCULATION: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    RESOURCES_UID: RAW(16) {constraint: [foreign_key]}
    RATE_SET_UID: RAW(16) {constraint: [foreign_key]}
    LINE: NUMBER(19,0)
    RESULT_FIELD: VARCHAR2
    RESULT_LABEL: VARCHAR2
    RESULT_CODE: VARCHAR2
    UNITS: VARCHAR2
    CURRENCY: NUMBER(1,0)
    SOURCE1: VARCHAR2
    SOURCE2: VARCHAR2
    SOURCE3: VARCHAR2
    SOURCE4: VARCHAR2
    SOURCE5: VARCHAR2
    SOURCE6: VARCHAR2
    SOURCE7: VARCHAR2
    SOURCE8: VARCHAR2
    SOURCE9: VARCHAR2
    SOURCE10: VARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    CALCFILE: VARCHAR2
    CECODE: VARCHAR2
    RATE_TABLE: VARCHAR2
  }

  RESOURCE_FILE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    DESCRIPTION: NVARCHAR2
    CODE_TYPE: VARCHAR2
    RATE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    RSLTALL: VARCHAR2
    RSLTCURR: VARCHAR2
    OWNER_USER_UID: RAW(16)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    CODELENGTH: NUMBER(19,0)
    LEVEL1: NUMBER(19,0)
    LEVEL10: NUMBER(19,0)
    LEVEL11: NUMBER(19,0)
    LEVEL12: NUMBER(19,0)
    LEVEL13: NUMBER(19,0)
    LEVEL14: NUMBER(19,0)
    LEVEL15: NUMBER(19,0)
    LEVEL16: NUMBER(19,0)
    LEVEL17: NUMBER(19,0)
    LEVEL18: NUMBER(19,0)
    LEVEL19: NUMBER(19,0)
    LEVEL2: NUMBER(19,0)
    LEVEL20: NUMBER(19,0)
    LEVEL3: NUMBER(19,0)
    LEVEL4: NUMBER(19,0)
    LEVEL5: NUMBER(19,0)
    LEVEL6: NUMBER(19,0)
    LEVEL7: NUMBER(19,0)
    LEVEL8: NUMBER(19,0)
    LEVEL9: NUMBER(19,0)
    MAX_LEVEL: NUMBER(19,0)
    PAD_CHAR: VARCHAR2
    TH_FLAGS: VARCHAR2
    RATEFILE: VARCHAR2
  }

  RESOURCE_FILE_COST_RESULT: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    RESOURCE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    RATE_SET_UID: RAW(16) {constraint: [foreign_key]}
    LINE: NUMBER(5,0)
    RESULT_FIELD: NVARCHAR2
    RESULT_LABEL: NVARCHAR2
    RESULT_CODE: NVARCHAR2
    UNITS: NVARCHAR2
    CURRENCY: NUMBER(1,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    CALCFILE: VARCHAR2
    RATETABLE: VARCHAR2
  }

}

# SpreadCurves Domain
spreadcurves: {
  label: "SpreadCurves Domain"
  SPREAD_CURVE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    NAME: NVARCHAR2
    POINTS: NUMBER(19,0)
    POINT_VALUES: NCLOB
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    SP_F1: NUMBER(19,0)
    SP_F10: NUMBER(19,0)
    SP_F11: NUMBER(19,0)
    SP_F12: NUMBER(19,0)
    SP_F13: NUMBER(19,0)
    SP_F14: NUMBER(19,0)
    SP_F15: NUMBER(19,0)
    SP_F16: NUMBER(19,0)
    SP_F17: NUMBER(19,0)
    SP_F18: NUMBER(19,0)
    SP_F19: NUMBER(19,0)
    SP_F2: NUMBER(19,0)
    SP_F20: NUMBER(19,0)
    SP_F21: NUMBER(19,0)
    SP_F22: NUMBER(19,0)
    SP_F23: NUMBER(19,0)
    SP_F24: NUMBER(19,0)
    SP_F25: NUMBER(19,0)
    SP_F26: NUMBER(19,0)
    SP_F27: NUMBER(19,0)
    SP_F28: NUMBER(19,0)
    SP_F29: NUMBER(19,0)
    SP_F3: NUMBER(19,0)
    SP_F30: NUMBER(19,0)
    SP_F31: NUMBER(19,0)
    SP_F32: NUMBER(19,0)
    SP_F33: NUMBER(19,0)
    SP_F34: NUMBER(19,0)
    SP_F35: NUMBER(19,0)
    SP_F36: NUMBER(19,0)
    SP_F37: NUMBER(19,0)
    SP_F38: NUMBER(19,0)
    SP_F39: NUMBER(19,0)
    SP_F4: NUMBER(19,0)
    SP_F40: NUMBER(19,0)
    SP_F41: NUMBER(19,0)
    SP_F42: NUMBER(19,0)
    SP_F43: NUMBER(19,0)
    SP_F44: NUMBER(19,0)
    SP_F45: NUMBER(19,0)
    SP_F46: NUMBER(19,0)
    SP_F47: NUMBER(19,0)
    SP_F48: NUMBER(19,0)
    SP_F49: NUMBER(19,0)
    SP_F5: NUMBER(19,0)
    SP_F50: NUMBER(19,0)
    SP_F51: NUMBER(19,0)
    SP_F52: NUMBER(19,0)
    SP_F6: NUMBER(19,0)
    SP_F7: NUMBER(19,0)
    SP_F8: NUMBER(19,0)
    SP_F9: NUMBER(19,0)
    SPREADORD: NUMBER(19,0)
  }

}

# Shared Domain
shared: {
  label: "Shared Domain"
  ACCESS_CONTROL_ENTRY: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    ENTITY_UID: RAW(16)
    USER_UID: RAW(16)
    GROUP_UID: RAW(16)
    ROLE_UID: RAW(16)
    VIEWONLY: NUMBER(1,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  USER_CODE_VALUE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PRIMARY_ENTITY_UID: RAW(16)
    ENTITY_UID: RAW(16)
    FIELD_NAME: NVARCHAR2
    CODE_UID: RAW(16) {constraint: [foreign_key]}
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  USER_FIELD_DEFINITION: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PRIMARY_ENTITY_UID: RAW(16)
    CODE_FILE_UID: RAW(16) {constraint: [foreign_key]}
    ENTITY_TYPE: VARCHAR2
    FIELD_NAME: VARCHAR2
    FIELD_LABEL: NVARCHAR2
    FIELD_DATA_TYPE: VARCHAR2
    REQUIRED: NUMBER(1,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    DESCRIPTION: NVARCHAR2
    SCOPE: VARCHAR2
  }

  USER_FIELD_VALUE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    PRIMARY_ENTITY_UID: RAW(16)
    ENTITY_UID: RAW(16)
    DATE1: DATE
    USER_FIELD_VALUES: NCLOB
    DATE2: DATE
    DATE3: DATE
    DATE4: DATE
    DATE5: DATE
    DATE6: DATE
    DATE7: DATE
    DATE8: DATE
    DATE9: DATE
    DATE10: DATE
    DATE11: DATE
    DATE12: DATE
    DATE13: DATE
    DATE14: DATE
    DATE15: DATE
    DATE16: DATE
    DATE17: DATE
    DATE18: DATE
    DATE19: DATE
    DATE20: DATE
    NUMBER1: NUMBER(21,6)
    NUMBER2: NUMBER(21,6)
    NUMBER3: NUMBER(21,6)
    NUMBER4: NUMBER(21,6)
    NUMBER5: NUMBER(21,6)
    NUMBER6: NUMBER(21,6)
    NUMBER7: NUMBER(21,6)
    NUMBER8: NUMBER(21,6)
    NUMBER9: NUMBER(21,6)
    NUMBER10: NUMBER(21,6)
    NUMBER11: NUMBER(21,6)
    NUMBER12: NUMBER(21,6)
    NUMBER13: NUMBER(21,6)
    NUMBER14: NUMBER(21,6)
    NUMBER15: NUMBER(21,6)
    NUMBER16: NUMBER(21,6)
    NUMBER17: NUMBER(21,6)
    NUMBER18: NUMBER(21,6)
    NUMBER19: NUMBER(21,6)
    NUMBER20: NUMBER(21,6)
    TEXT1: NVARCHAR2
    TEXT2: NVARCHAR2
    TEXT3: NVARCHAR2
    TEXT4: NVARCHAR2
    TEXT5: NVARCHAR2
    TEXT6: NVARCHAR2
    TEXT7: NVARCHAR2
    TEXT8: NVARCHAR2
    TEXT9: NVARCHAR2
    TEXT10: NVARCHAR2
    TEXT11: NVARCHAR2
    TEXT12: NVARCHAR2
    TEXT13: NVARCHAR2
    TEXT14: NVARCHAR2
    TEXT15: NVARCHAR2
    TEXT16: NVARCHAR2
    TEXT17: NVARCHAR2
    TEXT18: NVARCHAR2
    TEXT19: NVARCHAR2
    TEXT20: NVARCHAR2
    SEQUENCE: NUMBER(19,0)
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
  }

  USER_NOTE_VALUE: {
    shape: sql_table
    ROW_UID: RAW(16) {constraint: [primary_key]}
    SEQUENCE: NUMBER(19,0)
    PRIMARY_ENTITY_UID: RAW(16)
    ENTITY_UID: RAW(16)
    FIELD_NAME: NVARCHAR2
    CREATED_BY_USER_UID: RAW(16)
    CREATED_DATE: TIMESTAMP
    LAST_MODIFIED_BY_USER_UID: RAW(16)
    LAST_MODIFIED_DATE: TIMESTAMP
    FIELD_VALUE: NCLOB
  }

}

# Define relationships
codes.CODE_FILE -> codes.CODE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> codes.CODE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> codes.CODE_THRESHOLD: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR -> fiscal_calendars.FISCAL_CALENDAR_HOLIDAY: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR -> fiscal_calendars.FISCAL_CALENDAR_PERIOD: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR -> fiscal_calendars.FISCAL_CALENDAR_SET: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR_SET -> fiscal_calendars.FISCAL_CALENDAR_SET_LABEL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR_PERIOD -> fiscal_calendars.FISCAL_CALENDAR_SET_LABEL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.ACCOUNTS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.BATCHREP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.CHNG_REQST: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.CHNG_REQST_PROGRAM: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.CLASSRANGES: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP -> projects."LINK": {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects."LINK": {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROCESSLOG -> projects.PROCESSLOGLINK: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_FILE -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR -> projects.PROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_AUDIT_LOG: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_AUDIT_LOG_ACCOUNTS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_AUDIT_LOG_HISTORY: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_AUDIT_LOG_TPHASE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_AUDIT_LOG -> projects.PROJECT_AUDIT_LOG_TPHASE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_CALC_RESULT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CAWP: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP -> projects.PROJECT_CAWP_RESOURCE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCES -> projects.PROJECT_CAWP_RESOURCE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_COST_CLASS -> projects.PROJECT_CAWP_RESOURCE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

spreadcurves.SPREAD_CURVE -> projects.PROJECT_CAWP_RESOURCE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP_RESOURCE -> projects.PROJECT_CAWP_RESOURCE_TPHASE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP -> projects.PROJECT_CAWP_TOTAL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CONTROL_ACCOUNT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_CONTROL_ACCOUNT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_CONTROL_ACCOUNT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CONTROL_ACCOUNT -> projects.PROJECT_CONTROL_ACCOUNT_TOTAL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_COST_CLASS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_FILE -> projects.PROJECT_COST_CLASS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

fiscal_calendars.FISCAL_CALENDAR_SET -> projects.PROJECT_COST_CLASS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_COST_CLASS -> projects.PROJECT_COST_CLASS_LINK: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_COST_CLASS -> projects.PROJECT_COST_CLASS_LINK: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_COST_SET: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_COST_SET -> projects.PROJECT_COST_SET_CLASS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_COST_CLASS -> projects.PROJECT_COST_SET_CLASS: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_COST_TOTAL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_SUBPROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.PROJECT_SUBPROJECT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_WORK_PACKAGE -> projects.PROJECT_WORK_PACKAGE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_WORK_PACKAGE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CONTROL_ACCOUNT -> projects.PROJECT_WORK_PACKAGE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> projects.PROJECT_WORK_PACKAGE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_WORK_PACKAGE -> projects.PROJECT_WORK_PACKAGE_TOTAL: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_WORK_PACKAGE -> projects.PROJECT_WP_MILESTONE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT_CAWP -> projects.TEMP_CAWPID: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

projects.PROJECT -> projects.TEMP_CAWPID: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_SET -> rates.RATE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_FILE -> rates.RATE_SET: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCE_FILE -> resources.RESOURCES: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCES -> resources.RESOURCES: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCES -> resources.RESOURCE_COST_CALCULATION: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_SET -> resources.RESOURCE_COST_CALCULATION: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_FILE -> resources.RESOURCE_FILE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

resources.RESOURCE_FILE -> resources.RESOURCE_FILE_COST_RESULT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

rates.RATE_SET -> resources.RESOURCE_FILE_COST_RESULT: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE -> shared.USER_CODE_VALUE: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

codes.CODE_FILE -> shared.USER_FIELD_DEFINITION: {
  source-arrowhead: {
    shape: diamond
    style: {
      filled: true
    }
  }
  target-arrowhead: {
    shape: arrow
    style: {
      filled: false
    }
  }
  label: "has"
}

