--
-- Data_Oracle.sql
--
-- Target DBMS : Oracle
--
-- Copyright Deltek, Inc.
--
--
-- Script for creating default table data for the Cobra Web database.
--

DECLARE

--
-- Set the schema_name variable to the schema that will contain the tables if it is different from the schema that is executing this script.
-- For deployments that use the PPMADMIN and PPM schemas, the schema_name must be set to 'PPM'.
-- For deployments to a shared development database schema, the schema_name must be set to the developer's schema name.
-- For Liquibase deployments, the defaultSchemaName property can be set in the liquibase.properties file.
--
schema_name VARCHAR2(30);
--schema_name VARCHAR2(30) := '${database.defaultSchemaName}';
--schema_name VARCHAR2(30) := 'PPM';


--
-- PROCEDURE: INSERT_WST_TAB
--
--
-- Inserts records into the WST_TAB table
--
-- PROCEDURE INSERT_WST_TAB(
--     v_PRD_UID IN NUMBER,
--     v_VERSION IN CHAR,
--     v_TABLE_TYPE IN CHAR,
--     v_TABLE_NAME IN CHAR,
--     v_FLAGS IN NUMBER,
--     v_COTYPE IN CHAR
-- )
--     IS
--     x NUMBER;
-- BEGIN
--     SELECT ROWNUM INTO x FROM WST_TAB WHERE TABLE_NAME = v_TABLE_NAME AND TABLE_TYPE = v_TABLE_TYPE;
-- EXCEPTION
--     WHEN NO_DATA_FOUND THEN
--         BEGIN
--             INSERT INTO WST_TAB (PRD_UID, VERSION, TABLE_TYPE, TABLE_NAME, FLAGS, COTYPE)
--             VALUES (v_PRD_UID, v_VERSION, v_TABLE_TYPE, v_TABLE_NAME, v_FLAGS, v_COTYPE);
--         END;
-- END INSERT_WST_TAB;


--
-- PROCEDURE: INSERT_WST_DCT
--
--
-- Inserts records into the WST_DCT table
--
-- PROCEDURE INSERT_WST_DCT
-- (
--     v_TABLE_TYPE         IN VARCHAR2,
--     v_FLD_NAME           IN VARCHAR2,
--     v_TYPE               IN VARCHAR2,
--     v_LENGTH             IN NUMBER,
--     v_SCALE              IN NUMBER,
--     v_COL_FLAGS          IN NUMBER,
--     v_USR_NAME           IN VARCHAR2,
--     v_SYS_NAME           IN VARCHAR2,
--     v_STRING_ID          IN NUMBER,
--     v_FKEY_TABLE         IN VARCHAR2,
--     v_FKEY_FLD_NAME      IN VARCHAR2,
--     v_FKEY_REQUIRED      IN NUMBER,
--     v_FKEY_VIRTUAL       IN NUMBER
-- )
--     IS
--     x    NUMBER;
-- BEGIN
--     SELECT ROWNUM INTO x FROM WST_DCT WHERE TABLE_TYPE = v_TABLE_TYPE AND FLD_NAME = v_FLD_NAME;
-- EXCEPTION
--     WHEN NO_DATA_FOUND THEN
--         BEGIN
--             INSERT INTO WST_DCT(TABLE_TYPE, FLD_NAME, TYPE, LENGTH, SCALE, COL_FLAGS, USR_NAME, SYS_NAME, STRING_ID, FKEY_TABLE, FKEY_FLD_NAME, FKEY_REQUIRED, FKEY_VIRTUAL)
--             VALUES(v_TABLE_TYPE, v_FLD_NAME, v_TYPE, v_LENGTH, v_SCALE, v_COL_FLAGS, v_USR_NAME, v_SYS_NAME, v_STRING_ID, v_FKEY_TABLE, v_FKEY_FLD_NAME, v_FKEY_REQUIRED, v_FKEY_VIRTUAL);
--         END;
-- END INSERT_WST_DCT;

BEGIN

--
-- Alter session to set the current schema.
-- For Liquibase deployments, the defaultSchemaName property is set by the liquibase.properties file. So the ALTER SESSION statement is not needed.
IF schema_name IS NOT NULL THEN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ' || schema_name;
END IF;

--
-- WST_TAB table entries
--

-- CODE FILE TABLES
-- INSERT_WST_TAB (600,'5.0','CODE','CODE',0,'CODE_FILE');
-- INSERT_WST_TAB (600,'5.0','CODE_FILE_DETAIL','CODE_FILE_DETAIL',0,'CODE_FILE');
-- INSERT_WST_TAB (600,'5.0','CODE_THRESHOLD','CODE_THRESHOLD',0,'CODE_FILE');

-- DIRECTORY TABLE
-- INSERT_WST_TAB (600,'5.0','DIRECTORY','DIRECTORY',0,'');

-- FISCAL CALENDAR FILE TABLES
-- INSERT_WST_TAB (600,'5.0','FISCAL_CALENDAR_FILE_DETAIL','FISCAL_CALENDAR_FILE_DETAIL',0,'FISCAL_CALENDAR_FILE');
-- INSERT_WST_TAB (600,'5.0','FISCAL_HOLIDAY','FISCAL_HOLIDAY',0,'FISCAL_CALENDAR_FILE');
-- INSERT_WST_TAB (600,'5.0','FISCAL_PERIOD','FISCAL_PERIOD',0,'FISCAL_CALENDAR_FILE');
-- INSERT_WST_TAB (600,'5.0','FISCAL_SET','FISCAL_SET',0,'FISCAL_CALENDAR_FILE');
-- INSERT_WST_TAB (600,'5.0','FISCAL_SET_LABEL','FISCAL_SET_LABEL',0,'FISCAL_CALENDAR_FILE');

-- RATE FILE TABLES
-- INSERT_WST_TAB (600,'5.0','RATE','RATE',0,'RATE_FILE');
-- INSERT_WST_TAB (600,'5.0','RATE_SET','RATE_SET',0,'RATE_FILE');

--
-- WST_DCT table entries
--

-- CODE
-- INSERT_WST_DCT ('CODE','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CODE_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('CODE','PARENT_CODE_UID','GUID',16,0,0,'','',0,'CODE','ROW_UID',0,0);
-- INSERT_WST_DCT ('CODE','ID','TEXT',100,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','TAG','TEXT',60,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CODE_LEVEL','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CHILD_COUNT','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CHILD_POS','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

-- CODE_FILE_DETAIL
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','ROW_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','CODE_TYPE','TEXT',1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','PAD_CHAR','TEXT',1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','MAX_LEVEL','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','MAX_LENGTH','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','TH_FLAGS','TEXT',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','FIELD_NAME','TEXT',30,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','FIELD_DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL1','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL2','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL3','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL4','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL5','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL6','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL7','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL8','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL9','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL10','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL11','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL12','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL13','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL14','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL15','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL16','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL17','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL18','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL19','INTE',10,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_FILE_DETAIL','LEVEL20','INTE',10,0,0,'','',0,'','',0,0);


-- CODE_THRESHOLD
-- INSERT_WST_DCT ('CODE_THRESHOLD','ROW_UID','GUID',16,0,0,'','',0,'CODE','ROW_UID',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CODE_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPVF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPVU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPPF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPPU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCVF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCVU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCPF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCPU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPVF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPVU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPPF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPPU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCVF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCVU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCPF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCPU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAVF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAVU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAPF','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAPU','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPF_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SPU_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCF_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','SCU_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPF_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CPU_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCF_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CCU_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAF_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CAU_TL','TEXT',3,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('CODE_THRESHOLD','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);

--DIRECTORY
-- INSERT_WST_DCT ('DIRECTORY','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','ENTITY_TYPE','TEXT',30,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','ID','TEXT',100,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','OPENMODE','TEXT',1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','OWNER','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','CREATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','UPDATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('DIRECTORY','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

-- FISCAL_CALENDAR_FILE_DETAIL
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','ROW_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','PATTERN','TEXT',254,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_SUNDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_MONDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_TUESDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_WEDNESDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_THURSDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_FRIDAY','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_CALENDAR_FILE_DETAIL','HOURS_SATURDAY','DECI',6,2,0,'','',0,'','',0,0);

-- FISCAL_HOLIDAY
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','FISCAL_CALENDAR_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','HOLIDAY_DATE','DATE',100,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_HOLIDAY','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

-- FISCAL_PERIOD
-- INSERT_WST_DCT ('FISCAL_PERIOD','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','FISCAL_CALENDAR_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','END_DATE','DATE',100,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','HOURS','DECI',6,2,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_PERIOD','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);

-- FISCAL_SET
-- INSERT_WST_DCT ('FISCAL_SET','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','FISCAL_CALENDAR_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('FISCAL_SET','SET_ID','TEXT',6,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','LABEL_FORMAT','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

-- FISCAL_SET_LABEL
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','FISCAL_CALENDAR_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','FISCAL_SET_UID','GUID',16,0,0,'','',0,'FISCAL_SET','ROW_UID',1,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','FLAG','TEXT',1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','LABEL','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','CREATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','UPDATED_DATE','TSTP',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('FISCAL_SET_LABEL','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

--RATE
-- INSERT_WST_DCT ('RATE','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','RATE_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('RATE','RATE_SET_UID','GUID',16,0,0,'','',0,'RATE_SET','ROW_UID',1,0);
-- INSERT_WST_DCT ('RATE','RATE_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','RATE_VALUE','DECI',21,6,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','CREATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','UPDATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);

--RATE_SET
-- INSERT_WST_DCT ('RATE_SET','ROW_UID','GUID',16,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','SEQUENCE','INTE',38,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','RATE_FILE_UID','GUID',16,0,0,'','',0,'DIRECTORY','ROW_UID',1,0);
-- INSERT_WST_DCT ('RATE_SET','ID','TEXT',100,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','CREATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','CREATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','UPDATED_DATE','DATE',-1,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','UPDATED_BY','TEXT',20,0,0,'','',0,'','',0,0);
-- INSERT_WST_DCT ('RATE_SET','DESCRIPTION','TEXT',256,0,0,'','',0,'','',0,0);

COMMIT;
END;
